# Generated by Django 2.2 on 2021-01-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True),
        ),
    ]
