# Generated by Django 2.2 on 2021-01-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0002_auto_20210105_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
