# Generated by Django 2.2 on 2021-01-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0003_auto_20210105_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
    ]
