# Generated by Django 2.2 on 2021-01-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0006_auto_20210110_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id_categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
