# Generated by Django 2.2 on 2021-01-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0007_auto_20210111_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
