# Generated by Django 2.2 on 2021-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0014_auto_20210118_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default='2021-01-21'),
        ),
    ]
