# Generated by Django 2.2 on 2021-02-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0019_auto_20210205_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario_venta',
        ),
    ]
