# Generated by Django 2.2 on 2021-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0020_remove_venta_usuario_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='is_anulada',
            field=models.BooleanField(default=False),
        ),
    ]
