# Generated by Django 2.2 on 2021-02-11 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_project_app', '0021_venta_is_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='creacion_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creacion_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default='2021-02-10'),
        ),
    ]
