# Generated by Django 2.2 on 2021-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_project_app', '0022_auto_20210210_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_empleado',
        ),
    ]
